### PR TITLE
expose the terraform graph command

### PR DESCRIPTION
**Pull request by Velrok**
used to visualise the resouce dependency graph.
This allows one to see which things will be creates in parallel or in order.

### CODE REVIEW

**Comment by AgentAntelope** [comment]
might be nice to pull

```
if @options[:target]
  system("terraform plan -target=#{@options[:target]}")
else
  system("terraform plan")
end
```

into a method as it exists in a few places, otherwise 👍

**Comment by Velrok** [comment]
@AgentAntelope I would refer to the rule of 3 ;) and just leave it. Given that apply and destroy are also somewhat similar it would be a bit random to start to refactor some of the calls but not others. Again as soon as there is a 3rd repetition I would agree with you.
You OK with that?

**Comment by AgentAntelope** [comment]
@Velrok Actually the rule of three is what led me to that idea ;) `plan`, `apply` and now `graph` all have this `if` around the target options.

**Comment by AgentAntelope** [comment]
Looks great to me! 👍

**Pull request merged**
