### PR TITLE
Allow pushing terrafying to RubyGems and others

### PR DESCRIPTION
**Pull request by tombooth**

### CODE REVIEW

**Comment by AgentAntelope** [comment]
Why this change?

(relatedly: why was this the case in the first place?)

**Comment by tombooth** [comment]
Because we've pushed it to RubyGems. Don't know why originally, template?

**Comment by AgentAntelope** [comment]
Template definitely isn't to forbid this

**Comment by AgentAntelope** [comment]
But if we're happy ¯\_(ツ)_/¯

**Pull request merged**
